- name: Run Proxy
  community.docker.docker_container:
    name: httpd
    image: ryokenka/tp-devops-simple-api-httpd
    ports:
      - "80:80"
    networks:
      - name: my-network
    state: started

